"""Add imge url for user model

Revision ID: ef985d8bf8cd
Revises: 4beaa7a941e0
Create Date: 2024-10-11 23:23:33.226412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef985d8bf8cd'
down_revision = '4beaa7a941e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
